### ISSUE TITLE
添加订阅源不成功

### ISSUE THREAD

**Issue by Sky-nt** [Richasy/ReaderCopilot.Public#26]
最初从RSS追踪导出订阅源后添加 提示错误，然后一直刷新都是错误，索性就把软件卸载，然后重新安装。重新安装之后点击添加订阅源，没有反应，报错也没有了。然后查看了一下日志。
2023/12/02 09:39:31.183|Error|An exception occurred while the application was running|System.IO.DirectoryNotFoundException: Could not find a part of the path '........\RssCache\Local\rssCache.db'.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

2023/12/02 09:39:38.593|Error|An exception occurred while the application was running|System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by Sky-nt** [comment]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/28558097/e277775a-2b2d-400c-bc40-e51aa509f447)
手动添加分组，点击确定无反应
日志： 找不到对象
2023/12/02 10:10:06.153|Error|An exception occurred while the application was running|System.NullReferenceException: Object reference not set to an instance of an object.
   at ReaderCopilot.App.ViewModels.RssHomeViewModel.AddGroupAsync(RssFeedGroup group)
   at ReaderCopilot.App.Controls.Dialogs.RssGroupCreateDialog.OnPrimaryButtonClickAsync(ContentDialog sender, ContentDialogButtonClickEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2023/12/02 10:10:13.275|Error|An exception occurred while the application was running|System.NullReferenceException: Object reference not set to an instance of an object.
   at ReaderCopilot.Libs.DataService.RssDataService.GetFeedCacheAsync()
   at ReaderCopilot.Libs.RssService.LocalRssService.GetFeedListAsync()
   at ReaderCopilot.App.ViewModels.RssHomeViewModel.RefreshAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by Richasy** [comment]
😥没想到出这么大问题，抱歉。修，马上修，更新包已经上传了，这两天就能下载

**Comment by Sky-nt** [comment]
辛苦辛苦，等更新后，我再帮你测测😄
