### ISSUE TITLE
软禁下载重装更新后闪退

### ISSUE THREAD

**Issue by xillix-xillix** [Richasy/ReaderCopilot.Public#39]
日志如下:
2024/01/03 20:51:52.988|Error|An exception occurred while the application was running|System.TypeInitializationException: The type initializer for 'ReaderCopilot.App.ViewModels.AppViewModel' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ABI.System.DateTimeOffset.FromAbi(DateTimeOffset value)
   at ABI.System.Nullable_DateTimeOffset.GetValue(IInspectable inspectable)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.ComWrappersSupport.<>c__DisplayClass21_0.<CreateReferenceCachingFactory>b__0(IInspectable inspectable)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ComWrappers impl, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, Object wrapperMaybe, Object& retValue)
   at System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(IntPtr externalComObject, CreateObjectFlags flags)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at ABI.Windows.Foundation.Collections.IMapMethods`2.Lookup(IObjectReference obj, K key)
   at ABI.System.Collections.Generic.IDictionaryMethods`2.Lookup(IObjectReference obj, K key)
   at ReaderCopilot.App.Toolkits.SettingsToolkit.ReadLocalSetting[T](SettingNames settingName, T defaultValue)
   at ReaderCopilot.App.ViewModels.AppViewModel.<ResetGlobalSettings>g__AlignSetting|1_0[T](SettingNames name, T defaultValue)
   at ReaderCopilot.App.ViewModels.AppViewModel.ResetGlobalSettings()
   at ReaderCopilot.App.ViewModels.AppViewModel..cctor()
   --- End of inner exception stack trace ---
   at ReaderCopilot.App.Forms.MainWindow..ctor()
   at ReaderCopilot.App.App.LaunchWindowAsync(IActivatedEventArgs args)
   at ReaderCopilot.App.App.OnLaunched(LaunchActivatedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
2024/01/03 20:51:58.565|Error|An exception occurred while the application was running|System.TypeInitializationException: The type initializer for 'ReaderCopilot.App.ViewModels.AppViewModel' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ABI.System.DateTimeOffset.FromAbi(DateTimeOffset value)
   at ABI.System.Nullable_DateTimeOffset.GetValue(IInspectable inspectable)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.ComWrappersSupport.<>c__DisplayClass21_0.<CreateReferenceCachingFactory>b__0(IInspectable inspectable)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ComWrappers impl, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, Object wrapperMaybe, Object& retValue)
   at System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(IntPtr externalComObject, CreateObjectFlags flags)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at ABI.Windows.Foundation.Collections.IMapMethods`2.Lookup(IObjectReference obj, K key)
   at ABI.System.Collections.Generic.IDictionaryMethods`2.Lookup(IObjectReference obj, K key)
   at ReaderCopilot.App.Toolkits.SettingsToolkit.ReadLocalSetting[T](SettingNames settingName, T defaultValue)
   at ReaderCopilot.App.ViewModels.AppViewModel.<ResetGlobalSettings>g__AlignSetting|1_0[T](SettingNames name, T defaultValue)
   at ReaderCopilot.App.ViewModels.AppViewModel.ResetGlobalSettings()
   at ReaderCopilot.App.ViewModels.AppViewModel..cctor()
   --- End of inner exception stack trace ---
   at ReaderCopilot.App.Forms.MainWindow..ctor()
   at ReaderCopilot.App.App.LaunchWindowAsync(IActivatedEventArgs args)
   at ReaderCopilot.App.App.<>c__DisplayClass14_0.<<ActivateWindow>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)

**Comment by Richasy** [comment]
想确认一下：
1. 你的系统版本
2. 虽然你的标题提到了重装，但我不确定你之前安装的是不是旧版本。是否可以卸载应用后重启设备再安装？

**Comment by xillix-xillix** [comment]
系统版本是22631.2861
软件版本1.2401.1.0

**Comment by Richasy** [comment]
内测版本已经准备就绪，如果还没有进群，请加入 858688642 并申请内测
