### ISSUE TITLE
Win10下无法正常启动

### ISSUE THREAD

**Issue by axojhf** [Richasy/ReaderCopilot.Public#8]
我的Win10 22H2直接安装后点击APP无反应，尝试过在系统设置里将软件从C盘迁移到D盘，可以打开，但是点击“创建新库”或“打开库文件夹”没有反应，反正是无法使用，不知道这是我个人的问题还是兼容性的问题。

**Comment by axojhf** [comment]
日志：

```
2023/10/03 10:17:49.613|Info|App Launched: Launch|
2023/10/03 10:17:50.332|Error|An exception occurred while the application was running|System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 324
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 128
   at ReaderCopilot.App.App.LaunchWindow(IActivatedEventArgs args)
   at ReaderCopilot.App.App.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperWinUI.<.ctor>b__0_3(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
   at ABI.System.EventHandler`1.Do_Abi_Invoke[TAbi](Void* thisPtr, IntPtr sender, TAbi args)
```

**Comment by YangSuGuo** [comment]
我与它正好相反，软件在C盘可以正常打开，但是添加新库与打开库无反应。迁移至D盘无法打开（win10 22H2）可以远程
# 3130876713@qq.com

**Comment by Richasy** [comment]
此问题已修复，请更新至新版本（1.2310.2.0）
